---
title: "Cleaning"
output: 
  html_document:
    includes:
      in_header: "favicon.html"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(reticulate)
```

```{python include=FALSE}
import pandas as pd
import numpy as np
import dtale as dt
```

```{python include=FALSE}
bp_org = pd.read_csv("Blood_Pressure_data.csv", na_values = "?")
```


## Glimpse of the original Data set
Here are the first 10 rows from the original(uncleaned) data set

```{python}
bp_org.head(10)
```


## Summary of original Data
This is the information(summary) i.e. the uniques values and data types of each column in the original data.
```{python}
bp_org.info()
```

```{python}
bp = bp_org
#Type conversions
bp['cast'] = bp['cast'].astype('category')
bp['gender'] = bp['gender'].astype('category')
bp['age group'] = bp['age group'].astype('category')
bp['diag_1'] = bp['diag_1'].astype('category')
bp['diag_2'] = bp['diag_2'].astype('category')
bp['diag_3'] = bp['diag_3'].astype('category')
bp['max_glu_serum'] = bp['max_glu_serum'].astype('category')
bp['A1Cresult'] = bp['A1Cresult'].astype('category')
bp['glimepiride'] = bp['glimepiride'].astype('category')
bp['pioglitazone'] = bp['pioglitazone'].astype('category')
bp['rosiglitazone'] = bp['rosiglitazone'].astype('category')
bp['insulin'] = bp['insulin'].astype('category')
bp['glyburide-metformin'] = bp['glyburide-metformin'].astype('category')
bp['change'] = bp['change'].astype('category')
bp['Med'] = bp['Med'].astype('category')
bp['label'] = bp['label'].astype('category')
```


## Type conversions
Here we have converted the data types of required columns to their appropriate types.
You can compare these types with the summary provided above.
```{python}
bp.dtypes
```


## Deleting unneccesary columns
Here we are deleting the columns that are unnecessary, useless or those that have no impact on the data.
Reasons for the deletion of some of these columns can be seen in the Visualizations tab with their graphs.

These are the deleted columns: 

  * ['id', 'weight', 'discharge_disposition_id', 'admission_source_id', 'patient_no', 'admission_typeid','payer_code', 'medical_specialty',   'examide', 'citoglipton', 'repaglinide', 'nateglinide', 'chlorpropamide', 'acetohexamide', 'tolbutamide', 'acarbose', 'miglitol', 'troglitazone', 'tolazamide', 'glyburide', 'glipizide', 'glimepiride-pioglitazone', 'metformin', 'metformin-pioglitazone', 'metformin-rosiglitazone', 'glipizide-metformin','diag_1', 'diag_2', 'diag_3']
  
These are the columns left:
```{python}
#Deleting useless columns
cols_to_delete = ['id', 'weight', 'discharge_disposition_id', 'admission_source_id', 'patient_no', 'admission_typeid','payer_code', 'medical_specialty', 'examide', 'citoglipton', 'repaglinide', 'nateglinide', 'chlorpropamide', 'acetohexamide', 'tolbutamide', 'acarbose', 'miglitol', 'troglitazone', 'tolazamide', 'glyburide', 'glipizide', 'glimepiride-pioglitazone', 'metformin', 'metformin-pioglitazone', 'metformin-rosiglitazone', 'glipizide-metformin','diag_1', 'diag_2', 'diag_3']

bp = bp_org.drop(cols_to_delete, axis=1, inplace=False)

bp.columns
```


## Cleaned Data Set
Now a summary of the final version of the original data after it's cleaning phase can be seen here: 
```{python}
bp.info()
```
After the cleaning phase we see that we are now down to 21 columns and the data set is now a lot cleaner and neater than it was at the start.


## Labels modified
In the original data set the "Label" column has three categories i.e. '>5', '<30' and 'NO'

We have lumped the factors '>5' and '<30' in a new category names 'YES'.

So now the "Label" column has two categories i.e. 'YES' and 'NO'
```{python}
label_changed = {"label": {">5": "YES", "<30": "YES"}}
bp = bp.replace(label_changed)

bp.head(10)
```

Frequency Counts of the column “label”
```{python}
print(bp['label'].value_counts())
```

Null values count of Label:
```{python}
print("Null values count: ", bp['label'].isna().sum())
```


## Data set shape comparison
Shape of the original Data:
```{python}
print(bp_org.shape)
```

Shape of the cleaned Data:
```{python}
print(bp.shape)
```

```{python include=FALSE}
# df.to_csv(index=False)
bp.to_csv('/home/mahreen/Documents/bloodfast/bp.csv', index=False)
```

