---
title: "Statement"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Problem Statement

You have to perform a classification on provided dataset of Heart Attack prediction.

For that prediction, first of all you have to preprocess dataset and convert it into appropriate numeric form. Then you have to perform any Machine Learning model for the prediction of Label. 

## Desired Outcomes
1) Preprocessing

2) Apply more than 3 Machine Learning algorithms for the prediction and apply
majority voting concept for the final output. 

-> Majority voting means to take Predicted labels from all applied classifiers and assign final label according to majority vote.

3) Exploratory Data Analysis: Lot of graphs to understand the Data insights.

4) Accuracy, F Score more than 65 percent. 

->The more the F-score, more marks will be awarded.

## Note
You can use Numpy, Pandas, Sklearn, Matplotlib libraries for this project.

## Warning
In case of plagiarism you will be awarded 0 marks in Project and get F grade in Final exam too.
